version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80" # Expose port 80 for HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
